### ISSUE TITLE
kubelet fails to start

### ISSUE THREAD

**Issue by pohly** [clearlinux/cloud-native-setup#101]
I tried `vagrant up --provider=virtualbox` today. It updated to Clear Linux 29940. Then it failed with kubelet refusing to start:
```
    clr-01: Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service → /usr/lib/systemd/system/kubelet.service.
    clr-01: Created symlink /etc/systemd/system/multi-user.target.wants/crio.service → /usr/lib/systemd/system/crio.service.
    clr-01: Job for kubelet.service failed because the control process exited with error code.
    clr-01: See "systemctl status kubelet.service" and "journalctl -xe" for details.
```

Logging in and checking the journal shows:
```
Jun 17 14:27:20 clr-01 kubelet-version-check.sh[4166]: /usr/bin/kubelet-version-check.sh: line 8: /var/lib/kubelet/kubelet_version: No such file or directory
Jun 17 14:27:20 clr-01 kubelet[4165]: F0617 14:27:20.140206    4165 server.go:194] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kub>
```

`/var/lib/kubelet/config.yaml` does not exist.

**Comment by mcastelino** [comment]
@pohly we do not support virtualbox as it does not support all the features needed. Can you use libvirt?

**Comment by krsna1729** [comment]
Do we know if the issue is virtualbox or clearlinux version?

**Comment by krsna1729** [comment]
Since the only hypervisor specific stuff is this https://github.com/clearlinux/cloud-native-setup/blob/0e280f40fa21612f436b7f8d9257d3f850aba9c8/clr-k8s-examples/Vagrantfile#L65-L73

cluster init should ideally work unless i am missing something.

Kata for sure wont work since VBox doesnt support nested

**Comment by krsna1729** [comment]
We could move the cpu and memory out to be agnostic i think

**Comment by mcastelino** [comment]
Looks like we have an issue in Clearlinux itself

```
kubectl run -i --tty busybox --image=busybox --restart=Never -- sh
```

```
Error attaching, falling back to logs: error dialing backend: EOF
Error from server: Get https://192.52.100.12:10250/containerLogs/default/busybox/busybox: net/http: TLS
```

**Comment by pohly** [comment]
> we do not support virtualbox as it does not support all the features needed.

Fair enough. However, there might be users (like me) who just want to try out Kubernetes on Clear Linux without necessarily needing Kata Containers, so it would be nice to support also providers without nested virtualization.

> Can you use libvirt?

I'll have to install Vagrant differently then (binaries from https://www.vagrantup.com/downloads.html don't have it), but I can try. It's lower priority, though, because it looks like the issue that I was running into (https://github.com/clearlinux/distribution/issues/904) can be reproduced by the maintainer.

**Comment by ahsan518** [comment]
I think this issue is invalid, since we currently do not support virtualbox. Also verified, we are working on the vagrant setup to make sure its functional with Centos/Ubuntu/Clear.  Shall i close this ?

**Comment by mcastelino** [comment]
One option is to make kata optional and with that we may be able to support virtualbox.

**Comment by ganeshmaharaj** [comment]
Adding virtualbox option is fairly trivial. Like @krsna1729 mentioned, there are just a few things that are unique to libvirt. Let me try and push a patch enablign support for virtualbox.

**Comment by pohly** [comment]
`kubelet` seems to come up fine now.
