### ISSUE TITLE
Enable Ansible by adding switch for no terminal

### ISSUE THREAD

**Issue by jascott1** [clearlinux/cloud-native-setup#111]
Hi,

Currently the create_stack.sh script uses `[ -t 0 ]` to detect a terminal but this causes Ansible to hang when it tries to run create_stack.sh. I kludged it with a sed to make it never true but it would be preferable to have a flag to disable this check. Would a PR to add this flag be accepted or is there another mechanism we should use?

**Comment by krsna1729** [comment]
@jascott1 Feel free to send a PR :) A switch for non-interactive i am assuming?

**Comment by jascott1** [comment]
This landed w the Kustomize PR as `CLRK8S_NOPROMPT`.
