### ISSUE TITLE
metrics: ensure json int results are stored as ints

### ISSUE THREAD

**Issue by grahamwhaley** [clearlinux/cloud-native-setup#124]
Some of the JSON results from the metrics are `ints` but are being stored in the JSON as strings:

```json
"Config": [
                        {
                "testname": "k8s scaling",
                "NUM_PODS": "5",
                "STEP": "1",
                "wait_time": "30",
                "delete_wait_time": "600",
                "settle_time": "5"
        }
        ],
```

This makes the default data import/index/mappings in say elasticsearch pick up the wrong 'type', which then prevents (or makes hard) the use of that data as ints (and thus aggregation, math, graphing) in tools like kibana and grafana.

Go through the JSON output and ensure everything that is or can be an `int` is...

**Comment by dklyle** [comment]
This merged didn't it?  Can we close?

**Comment by grahamwhaley** [comment]
It did - I probably forgot to add a Fixes to the PR.... closing....
