### ISSUE TITLE
Vagrant error with proxy

### ISSUE THREAD

**Issue by knangia** [clearlinux/cloud-native-setup#133]
When running this : “**vagrant up --provider=libvirt**”, there is an error returned by vagrant
 
Vagrant failed to initialize at a very early stage:
 
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.
 
Path: /home/khanak/new-setup/cloud-native-setup/clr-k8s-examples/Vagrantfile
Line number: 0
Message: undefined local variable or method `proxy_ip_list'

There is some issue with this line https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/Vagrantfile#L84 .
c.proxy.no_proxy =  (ENV['no_proxy']+"#{proxy_ip_list}" || ENV['NO_PROXY']+"#{proxy_ip_list}" || "localhost,127.0.0.1,172.16.10.10#{proxy_ip_list}")

**Comment by CraigSterrett** [comment]
I have submitted a PR for this, but have now run into the next proxy issue and created a new issue for that.

**Comment by knangia** [comment]
Thanks Craig! LGTM
