### ISSUE TITLE
podSubnet in kubeadm.yaml ignored

### ISSUE THREAD

**Issue by dklyle** [clearlinux/cloud-native-setup#148]
The value set specified for the podSubnet is: 
podSubnet: 10.244.0.0/16

When the cluster comes up via `create_stack.sh minimal` and even when running `kubeadm init --config ./kubeadm.yaml`, the result in `kubectl describe pod <leader-node-name>` gives:
PodCIDR:                     10.244.0.0/24

When the cluster is up with canal configured, the max pod count is 256 which matches 10.244.0.0/24.

**Comment by NitinAtIntel** [comment]
I can take a look at this

**Comment by krsna1729** [comment]
@dklyle in the above command did you mean `kubectl describe node <leader-node-name>`?

If so the behavior is correct. The kubeadm.yaml is specifying the subnet for pods across the entire cluster. This gets divided by into /24 subnets pool per node

**Comment by dklyle** [comment]
@krsna1729 you are correct, sorry for the noise. I missed setting 

```
controllerManager:
  extraArgs:
    node-cidr-mask-size: "20"
```

in kubeadm.yaml.

I will say I could not find any upstream K8s documentation that describes the behavior as you described it. Thanks for the clarification. I will close this now.

**Comment by krsna1729** [comment]
@dklyle now worries. Yup had dig through quite a bit the first time i had to support more that 254 pods. @grahamwhaley needed it too for his tests.

**Comment by NitinAtIntel** [comment]
Thanks folks, we're just trying to slam through these issues so are grabbing whatever we think is relevant :) - so thanks for closing and sorry for churn on assignment.
