### ISSUE TITLE
Discuss version pinning in the yamls

### ISSUE THREAD

**Issue by krsna1729** [clearlinux/cloud-native-setup#15]
As per this comment  https://github.com/clearlinux/cloud-native-setup/issues/13#issuecomment-445370890 we want to avoid version pins. Today all yamls have `image` pinned since its considered best practice, and the yamls themselves pin the api versions of the different kubernetes objects they create. Since k8s versions will keep moving forward with clear, we need a way to keep these yamls up-to-date too.

What is the plan for upgrading the yamls?
- Should we register an endpoint for each directory and check for updates?
- Should we leverage helm for getting latest stable yamls where possible?

Available helm charts -
- [rook-operator](https://rook.io/docs/rook/v0.9/helm-operator.html) (does not include cluster and storageclass manifests)
- [metrics-server](https://github.com/helm/charts/tree/master/stable/metrics-server)
- [kubernetes-dashboard](https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard)
- [fluentd-elasticsearch](https://github.com/helm/charts/tree/master/stable/fluentd-elasticsearch)
- [kibana](https://github.com/helm/charts/tree/master/stable/kibana)
- [prometheus-operator and kube-prometheus](https://github.com/helm/charts/tree/master/stable/prometheus-operator)
- [nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress)
- [metalLB](https://github.com/helm/charts/tree/master/stable/metallb)

@mcastelino

**Comment by krsna1729** [comment]
Also what is the user story with respect to these yamls? How much overlap is this with Helm?

Should a new issue be created?

**Comment by jascott1** [comment]
@krsna1729 As all of these components' versions are explicit in `create_stack.sh` and we have a pattern for updating supported versions, can we close this?

**Comment by krsna1729** [comment]
SGTM
