### ISSUE TITLE
Adding Intel contributions to k8s stack

### ISSUE THREAD

**Issue by krsna1729** [clearlinux/cloud-native-setup#16]
@mcastelino /cc @amshinde

Add an upgraded version of [amshinde/kata-sriov-dp](https://github.com/amshinde/kata-sriov-dp) which has example manifests for deploying Multus-CNI, SRIOV-CNI and sriov device plugin. Optionally, include manifests for intel-device-plugins-for-kubernetes and userspace-cni-network-plugin

Also look into enabling CPUManager by default in the kubelet configuration along with #8 
```
  --cpu-manager-policy=static 
  --cpu-manager-reconcile-period=5s 
```

**Comment by mythi** [comment]
We also have:
https://github.com/kubernetes-sigs/node-feature-discovery

and maybe later:
https://github.com/intel/intel-device-plugins-for-kubernetes
