### ISSUE TITLE
Would like to have Crio as default not containerd

### ISSUE THREAD

**Issue by CraigSterrett** [clearlinux/cloud-native-setup#176]
I would like crio to be the default container runtime in setup_system.sh

**Comment by dklyle** [comment]
Why on the first part? 

And the second part already exists: https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/setup_system.sh#L13
Just set the environment variable RUNNER=crio when running

**Comment by CraigSterrett** [comment]
Yeah my mistake I deleted the second part.
As far as crio, oci hook support for FPGA, and future support for openshift.

**Comment by msivosuo** [comment]
Also oci hook support for containerd is being discussed in upstream. See: https://github.com/containerd/cri/pull/1248

**Comment by CraigSterrett** [comment]
Closed with PR https://github.com/clearlinux/cloud-native-setup/pull/208
