### ISSUE TITLE
support for non-uniform VM CPU and Memory sizes in vagrantfile

### ISSUE THREAD

**Issue by dklyle** [clearlinux/cloud-native-setup#177]
It would be nice to have the option to override the CPU and Memory sizes likely per an array env variable so that all systems didn't have the same CPU count and memory sizes when using the vagrantfile.

**Comment by ahsan518** [comment]
So the way vagrant file is written: We can use different CPU and Memory for different VM's when spinning up:

CPU=4 MEMORY=8096 vagrant up clr-01
CPU=8 MEMORY=8096 vagrant up clr-02
CPU=4 MEMORY=4048 vagrant up clr-03

Hope this works. 
Pushed a patch with updated readme for vagrant.md

**Comment by knangia** [comment]
#194 is merged, hence closing this issue.
