### ISSUE TITLE
'dirty' nodes need /var/lib/rook deleting

### ISSUE THREAD

**Issue by grahamwhaley** [clearlinux/cloud-native-setup#18]
If you tear down and try to re-join a slave/node then it may fail to bring up `ceph-rook` (fairly silently), as the installation may find an existing `/var/lib/rook` directory, and fail to initialise.
We should see if we can find a way to remove the `/var/lib/rook` *or* error out nicely when initialising or joining nodes, somehow.

**Comment by krsna1729** [comment]
@grahamwhaley
Is this already addressed with the reset script?
https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/reset_stack.sh#L40

**Comment by krsna1729** [comment]
Yup added complexity. kubectl, awk, xargs, ssh should be enough

**Comment by krsna1729** [comment]
@mcastelino

**Comment by krsna1729** [comment]
@grahamwhaley we can just run the reset_stack.sh right? Can we close this?

**Comment by ganeshmaharaj** [comment]
@krsna1729 would be nice to add logic to clean `/var/lib/rook` from all the nodes. Maybe find list of nodes when reset_stack.sh is called and do the ssh + delete at the end of the script after kube is reset?

**Comment by grahamwhaley** [comment]
@krsna1729 @ganeshmaharaj - adding to `reset_stack.sh` is the ideal, because that is notionally when you want to do that cleanup... but, that is harder as you have to get all the ssh setup etc.
That's why I was suggesting adding it to the `setup_system.sh` as a sort of 'pre-sanity clean check`, as the time this presents as a real problem is when re-installing a node, so that script would be run, and can clean up any old rook dirs before trying to re-install anew. Much easier to code up.

**Comment by krsna1729** [comment]
@grahamwhaley add it to `setup_system.sh` with a TODO to remove it in future. From rook documentation - 
```
Connect to each machine and delete /var/lib/rook, or the path specified by the dataDirHostPath.
In the future this step will not be necessary when we build on the K8s local storage feature.
````

**Comment by jascott1** [comment]
Im not set against but seems like it should be in `reset_stack.sh` and called by something like Ansible for each node. IMO we should not implement multi-node management in bash just to remove `/var/lib/rook`. It also leaves it decoupled for user to use the tool of their choice.

**Comment by ahsan518** [comment]
Should we add this in Ansible, or make the changes in the script ?

**Comment by knangia** [comment]
We have this https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/reset_stack.sh#L43 in reset_stack script already.

**Comment by knangia** [comment]
closing this, open this if still active.
