### ISSUE TITLE
Standardize on shell style

### ISSUE THREAD

**Issue by jascott1** [clearlinux/cloud-native-setup#180]
We should publish our requirements for formatting shell scripts. I propose we use something akin to an industry standard. Shfmt [docs](https://github.com/mvdan/sh#shfmt) reference the [Google Style Guide](https://google.github.io/styleguide/shell.xml#Indentation). I vote for 2 spaces over tabs `shfmt -i 2 -ci`.

**Comment by krsna1729** [comment]
Thanks for raising this. Once decided we should provide git hooks to help locally and maybe travis or github actions to enforce on PR

**Comment by jascott1** [comment]
Also, If we are going to gate on `shellcheck` we should provide the config.

**Comment by jascott1** [comment]
@krsna1729 @ganeshmaharaj @dklyle @obedmr  if you have any comments on code formatting etc. it would be great to hear them!

**Comment by krsna1729** [comment]
I am ok with current one or what you are proposing. Lets just document and provides hooks. I am good.
