### ISSUE TITLE
Clear Linux update

### ISSUE THREAD

**Issue by mythi** [clearlinux/cloud-native-setup#198]
The previous update was done in July:
https://github.com/clearlinux-pkgs/cloud-native-setup/commits/master

**Comment by NitinAtIntel** [comment]
Thanks @mythi I'm working on this and will refer to this issue on any PRs

**Comment by NitinAtIntel** [comment]
All updates have been pushed, just waiting on Docker in a new build, @mythi . Once Docker updates via swupd I will post here for you to verify, sound good?

**Comment by mythi** [comment]
@NitinAtIntel Is cloud-native-setup (this repo) also updated?

**Comment by CraigSterrett** [comment]
I think the question is have we update https://github.com/clearlinux-pkgs/cloud-native-setup and that answer appears to be no

**Comment by NitinAtIntel** [comment]
I see what you mean now, @mythi, I will work on that part of it today and update this.

**Comment by NitinAtIntel** [comment]
I've updated Clear, awaiting CI and will close this when we have a release with everything.

**Comment by NitinAtIntel** [comment]
Verified updated in 31380 to v1.7 of cloud-native-setup
