### ISSUE TITLE
Stop referencing deprecated beta workload APIs

### ISSUE THREAD

**Issue by CraigSterrett** [clearlinux/cloud-native-setup#220]
Kubernetes 1.16 ended support for v1beta1 and v1beta2 API. These references need to be updated in all files

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

The following APIs are no longer served by default:

All resources under apps/v1beta1 and apps/v1beta2 - use apps/v1 instead
daemonsets, deployments, replicasets resources under extensions/v1beta1 - use apps/v1 instead
networkpolicies resources under extensions/v1beta1 - use networking.k8s.io/v1 instead
podsecuritypolicies resources under extensions/v1beta1 - use policy/v1beta1 instead

./clr-k8s-examples/admit-kata/deploy/webhook-registration.yaml.tpl(5): apiVersion: admissionregistration.k8s.io/v1beta1
./clr-k8s-examples/7-rook/overlays/v0.8.3/patch_operator.yaml(2): apiVersion: apps/v1beta1
./clr-k8s-examples/admit-kata/deploy/webhook.yaml(5): apiVersion: extensions/v1beta1
./clr-k8s-examples/tests/deploy-svc-ing/test-ingress-kata.yaml(1): apiVersion: extensions/v1beta1
./clr-k8s-examples/tests/deploy-svc-ing/test-ingress-runc.yaml(1): apiVersion: extensions/v1beta1

**Comment by knangia** [comment]
created PR #259
