### ISSUE TITLE
Canal CNI: calico-node container not Ready on a bare-metal cluster

### ISSUE THREAD

**Issue by askervin** [clearlinux/cloud-native-setup#229]
Canal CNI setup (by `create_stack.sh`) fails to connect the master node host traffic to pods on the worker node on a bare metal cluster. The same version works fine on Qemu/KVM master and worker nodes.

```
hw-master$ kubectl get pods -n kube-system
NAME                                   READY   STATUS    RESTARTS   AGE
canal-f9mg4                            1/2     Running   0          5h24m
canal-hvdnd                            1/2     Running   1          5h23m
```

```
vm-master$ kubectl get pods -n kube-system
NAME                              READY   STATUS    RESTARTS   AGE
canal-6qqm2                       2/2     Running   0          4h36m
canal-h8qxk                       2/2     Running   0          4h36m
```

Pod-to-pod connections work fine on both clusters, at least within the worker node. netcat on vm-master can connect to pod IPs (10.244.16.0/20) directly, but result in timeout on hw-master.

The `calico-node` container inside `canal-xxxxx` pods is in `Ready: false` state on the hw cluster, but there is `calico-node -felix` process running on both nodes in the hw cluster, but `Ready: true` on the vm cluster.

More detailed logs attached:

[calico-vm-vs-hw.tar.gz](https://github.com/clearlinux/cloud-native-setup/files/3750763/calico-vm-vs-hw.tar.gz)

Setup was run from commit f2e89413ad70d06a60d49d8bf7502f265464008d.

**Comment by jascott1** [comment]
Hi @askervin

 I have no idea whats going wrong but could you attach your `journalctl` from master and a node?

**Comment by jascott1** [comment]
@askervin Still experiencing the issue?

**Comment by ahsan518** [comment]
Tested on baremetal servers, works as expected. Kindly let me know if it still pertains

**Comment by askervin** [comment]
There were some issues in the hw network setup (overlapping IP subnets). I cannot reproduce the problem after the network fixes anymore. Thanks for your support, sorry about the trouble.
