### ISSUE TITLE
Enable CSI storage

### ISSUE THREAD

**Issue by mythi** [clearlinux/cloud-native-setup#30]
It's useful to have a CSI based storage enabled. CSI reached 1.0/GA in 1.13.

**Comment by mcastelino** [comment]
@mythi yes we should definitely add that given that clear will move to 1.13 soon.

**Comment by krsna1729** [comment]
@mcastelino clear is already on 1.13

**Comment by mythi** [comment]
Clear is already @v1.13.1

**Comment by krsna1729** [comment]
@ganeshmaharaj
https://github.com/rook/rook/issues/1385
https://github.com/rook/rook/blob/master/design/ceph-csi-driver.md

**Comment by jascott1** [comment]
@mythi is this satisfied with Rook now?

**Comment by mythi** [comment]
> @mythi is this satisfied with Rook now?

No. v1.0.3 does not seem to enable CSI. :

```
# Also see other operator sample files for variations of operator.yaml:
# - operator-openshift.yaml: Common settings for running in OpenShift
# - operator-with-csi.yaml: Enable the ceph-csi driver
```

I can see master enables CSI by default (since two days ago).

**Comment by jascott1** [comment]
@mythi I have an incoming PR that enables Rook CSI. Do you have anything specific you wanted to test with it?
