### ISSUE TITLE
rook: fails to come up on single node cluster

### ISSUE THREAD

**Issue by grahamwhaley** [clearlinux/cloud-native-setup#306]
Setting up a single node cluster (that is, not joining any slave nodes at the point where the setup pauses for you to) of 'all' using create_stack.sh, the process gets stuck 'forever' trying to bring up rook:

```
...
rolebinding.rbac.authorization.k8s.io/rook-ceph-mgr created
rolebinding.rbac.authorization.k8s.io/rook-ceph-osd created
rolebinding.rbac.authorization.k8s.io/rook-ceph-system created
clusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-nodeplugin created
clusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-provisioner-role created
clusterrolebinding.rbac.authorization.k8s.io/rbd-csi-nodeplugin created
clusterrolebinding.rbac.authorization.k8s.io/rbd-csi-provisioner-role created
clusterrolebinding.rbac.authorization.k8s.io/rook-ceph-system-psp created
clusterrolebinding.rbac.authorization.k8s.io/rook-csi-cephfs-plugin-sa-psp created
clusterrolebinding.rbac.authorization.k8s.io/rook-csi-cephfs-provisioner-sa-psp created
clusterrolebinding.rbac.authorization.k8s.io/rook-csi-rbd-plugin-sa-psp created
clusterrolebinding.rbac.authorization.k8s.io/rook-csi-rbd-provisioner-sa-psp created
clusterrolebinding.rbac.authorization.k8s.io/rook-ceph-global created
clusterrolebinding.rbac.authorization.k8s.io/rook-ceph-mgr-cluster created
clusterrolebinding.rbac.authorization.k8s.io/rook-ceph-object-bucket created
clusterrolebinding.rbac.authorization.k8s.io/rook-ceph-osd created
deployment.apps/rook-ceph-operator created
cephblockpool.ceph.rook.io/replicapool created
cephcluster.ceph.rook.io/rook-ceph created
podsecuritypolicy.policy/rook-privileged created
No resources found
Waiting for Rook OSD
Waiting for Rook OSD
^C
```

For ref:

```
$ sudo swupd update -s
Current OS version: 32230
Latest server version: 32230
There are no updates available
```

I don't know if that is specific to my system, or due to being a single node. I'm pretty sure this used to work. If you need me to re-try etc., then tell me what to try and I'll log back here.

**Comment by CraigSterrett** [comment]
There is an issue with starting up the rook-ceph-mon pods, it tries to start two (for quorum) but one stays pending due to an anti-affinity of not running two copies of the monitor on the same node. I have actually not run single node before so not sure this would have ever worked.  @jascott1 maybe has more information

**Comment by nklayman** [comment]
I got this issue on a completely fresh install of clear linux (single node).

**Comment by CraigSterrett** [comment]
Looks like we will have to fix this

Use the cluster-test.yaml when your Kubernetes cluster has less than 3 schedulable Nodes (e.g., minikube)! When using the cluster-test.yaml only one mon is started. If that mon is down for whatever reason, the Ceph Cluster will come to a halt to prevent any data “corruption”.
