### ISSUE TITLE
consider adding 'easyrsa', to enable juju k8s e2e workflow

### ISSUE THREAD

**Issue by grahamwhaley** [clearlinux/cloud-native-setup#31]
Looking at how to run the k8s [e2e tests](https://kubernetes.io/docs/getting-started-guides/ubuntu/validation/) (note, that is an ubuntu specific page, but I'm struggling to find a more generic k8s e2e test page right now), it notes that one should `relate the kubernetes-e2e charm to your existing kubernetes-master nodes and easyrsa`.
@ganeshmaharaj also notes that `easyrsa` is one of the options for [client certificate authentication](https://kubernetes.io/docs/concepts/cluster-administration/certificates/), which is a requirement for any level of 'production ready' stack up.

Should we consider adding `easyrsa` to our stackup?

**Comment by grahamwhaley** [comment]
oops, must have accidentally pressed close...
... until we answer the question of do we need to add easyrsa or not.

**Comment by krsna1729** [comment]
@grahamwhaley seems like `openssl` is installed in the current setup. Would that be enough to address the client certificate link?

**Comment by krsna1729** [comment]
@grahamwhaley closing this as openssl is sufficient to run https://github.com/kata-containers/tests/pull/1082
