### ISSUE TITLE
Useful addons

### ISSUE THREAD

**Issue by krsna1729** [clearlinux/cloud-native-setup#34]
Has anyone looked at https://github.com/kubernetes/node-problem-detector? Would it be useful to package?

Also should we look at using sources from this directory for addons testing?
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons

especially dashboard

@mcastelino

**Comment by jascott1** [comment]
@mcastelino We now have several add-ons (prometheus, dashboard, metrics etc.) are we still interested in adding this? If so I will create a PR.

**Comment by krsna1729** [comment]
dashboard is already present
#116 takes care of node-problem-detector

**Comment by jascott1** [comment]
Hi @krsna1729 I submitted #160 to supersede @mcastelino 's PR using the new pattern in create_stack.sh. Please let me know what you think.

**Comment by jascott1** [comment]
@krsna1729 Closing as we have add-ons. Please reopen if necessary.
