### ISSUE TITLE
Add licence files from upstream repos

### ISSUE THREAD

**Issue by krsna1729** [clearlinux/cloud-native-setup#4]

**Comment by jascott1** [comment]
Hi @krsna1729 

Did you create [9-multi-network](https://github.com/clearlinux/cloud-native-setup/tree/master/clr-k8s-examples/9-multi-network) or do you know of the original source where we can find a license?

**Comment by krsna1729** [comment]
@jascott1 no single source for the folder

**Comment by krsna1729** [comment]
dockerfile, scripts, documentation etc., are all original. yaml some snippets are from multus

**Comment by jascott1** [comment]
@krsna1729 Since we moved to Kustomize, I only found one license to add.

**Comment by krsna1729** [comment]
Sounds good we can close this

**Comment by krsna1729** [comment]
forgot there is PR referencing this

**Comment by jascott1** [comment]
PR has been closed also.
