### ISSUE TITLE
containerd: containerd-shim-v2

### ISSUE THREAD

**Issue by mcastelino** [clearlinux/cloud-native-setup#43]
Kata now supports containerd-shim-v2. We need to support this setup as it will allow us to do proper resource accounting. We will need to hold containerd at the version that supports device mapper, so this is not ideal from a security point of view. But it is useful for us to ensure that auto-scaling and resource accounting is stress tested with kata.

**Comment by egernst** [comment]
@mcastelino - we can try to configure the aws snapshotter plugin?

**Comment by NitinAtIntel** [comment]
@mcastelino Is this still an open?

**Comment by knangia** [comment]
closing this, since obsolete
