### ISSUE TITLE
Cleanup Vagrantfile

### ISSUE THREAD

**Issue by krsna1729** [clearlinux/cloud-native-setup#44]
Since we made switch to @AntonioMeireles's boxes, lets take opportunity to cleanup Vagrantfile for redundant proxy, unused disk/network configs

**Comment by ganeshmaharaj** [comment]
@krsna1729 might i bother you to elaborate? the proxy settings in our Vagrantfile is still needed as that needs to be passed to the new box as well. the reason for adding more drives to each machine was to let rook consume them and use them. if we are going to let rook not use it then we can get rid of them.

**Comment by krsna1729** [comment]
@AntonioMeireles was mentioning something about proxy stuff being redundant, but yeah it would still be required.

**Comment by krsna1729** [comment]
Extra disk will be needed for ceph and network is currently not used in k8s but will be used for future work you said. Guess there nothing to remove!

**Comment by krsna1729** [comment]
@ganeshmaharaj

**Comment by krsna1729** [comment]
@ganeshmaharaj this can be closed right :P :)

**Comment by NitinAtIntel** [comment]
@ganeshmaharaj Can this be closed?

**Comment by ganeshmaharaj** [comment]
@NitinAtIntel been a while wince i reviewed them all. are you seeing changes in the Vagrantfile that are redundant that can be removed? If so, i think we can.

**Comment by ahsan518** [comment]
Seems like we can close this as i dont feel there is much to do in Vagrant file. Will wait for team's feedback before closing this Issue.
