### ISSUE TITLE
Test and document how Clear OS updates affect stack

### ISSUE THREAD

**Issue by krsna1729** [clearlinux/cloud-native-setup#53]
Document ugrade path for system components to limit downtime.

**Comment by mcastelino** [comment]
@krsna1729 and reboots too, specially with kata and crio

**Comment by mythi** [comment]
https://clearlinux.org/documentation/clear-linux/tutorials/kubernetes/kubernetes-bp#kubernetes-bp

**Comment by mcastelino** [comment]
@krsna1729 we should should be able to reuse the kata-deploy logic to facilitate this?

**Comment by NitinAtIntel** [comment]
@ganeshmaharaj @mcastelino given @mythi's link, is anything left to do on this?

**Comment by ahsan518** [comment]
Closing this issue.
