### ISSUE TITLE
kubeadm init in ./create_stack.sh fails

### ISSUE THREAD

**Issue by hnanni** [clearlinux/cloud-native-setup#65]
After a succesfull execution of cloud-native-setup/clr-k8s-examples/setup_system.sh; the "kubeadm init" call from create_stack.sh minimal reports the following error:

error execution phase upload-config/kubelet: Error writing Crisocket information for the control-plane node: timed out waiting for the condition
Do you know what I need to setup in order to have the problem fixed?

Full log is in: https://github.intel.com/gist/anonymous/476dd91c52ca3a9a3ecfb69d6394ec62

**Comment by krsna1729** [comment]
@hnanni Initial suspicion is proxy.

**Comment by ganeshmaharaj** [comment]
@hnanni i think this is specific to proxy. There is one problem with this setup when we are behind proxy. All the VMs come up with two IPs. one that is native to vagrant & libvirt which you as the user has no control over or have an automated way of knowing what it is (Atleast i haven't figured it out yet). The second is the one that is added as a private network by the file which we can give specific IP addresses for.  Why this affects us here? <-- The IP that we get from vagrant & libvirt is the one that is used as a primary IP and we need to add it to the no_proxy list (it is not there when the VMs come up for the first time.

You might need to do these steps.
` vagrant ssh-config` [Run this from the folder where the `Vagrantfile` lives.  This will list all the vms that are running and their IPs. Create a comma separated list of these and add them the following files in all the VMs.
```
/etc/environment
/etc/profile.d/proxy.sh
/etc/systemd/system/kubelet.service.d/proxy.conf
/etc/systemd/system/crio.service.d/proxy.conf
```
restart both crio and kubelet and then try this again.

I *really* wish was an automated way to add these to the vms, but i am unable to find one. If you have any ideas on this,  i would love to fix this issue.

**Comment by hnanni** [comment]
thanks @krsna1729 , @ganeshmaharaj 

I'm in bare metal and without vagrant (I have it not yet ready in clear linux)

The /etc/profile.d/proxy.sh is created upon system boot in order to get the machine IP updated in the no_proxy|NO_PROXY fields. I source that file before setup_system.sh in order the script get the $PROXIES in the env and the /etc/systemd/system/[kubelet|crio].service.d/proxy.conf files it creates, get the machine IP in the no_proxy

I've pasted the contents of the proxy config files/environment in the gist.
Redid all, but I I keep getting the same error mesage from kubeadm init --config=./kubeadm.yaml

If I keep wo vagrant/libvirt and only qemu, the automation for the no_proxy setup seems to be automatable (when master and workers run in a private vlan), but I'm still on the baremetal setup exercise

**Comment by hnanni** [comment]
Problem is not showing after having upper and lower case proxy specifications in 
`/etc/systemd/system/[kubelet|crio].service.d/proxy.conf`

**Comment by krsna1729** [comment]
@ganeshmaharaj should we add this?

**Comment by mythi** [comment]
FWIW, I have only upper case  (for crio only, kubelet does not need proxy settings) and that works.

IMO, what ever we can do yo make this less error prone is always better. However, I'm not yet sure what to change.
