### ISSUE TITLE
Figure out dashboard privileges, currently cluster-admin

### ISSUE THREAD

**Issue by krsna1729** [clearlinux/cloud-native-setup#7]
Currently we are getting dashboard to work by giving sudo privileges [`2-dashboard/dashboard-admin.yaml`](cloud-native-setup/clr-k8s-examples/2-dashboard/dashboard-admin.yaml). Need to address this

**Comment by krsna1729** [comment]
http://blog.cowger.us/2018/07/03/a-read-only-kubernetes-dashboard.html

**Comment by jascott1** [comment]
@krsna1729 Do you think this might be obsolete now that dashboard v2 (currently beta3) has finer grain permissions? https://github.com/kubernetes/dashboard/blob/v2.0.0-beta3/aio/deploy/recommended.yaml#L123

**Comment by krsna1729** [comment]
Yes!
