### ISSUE TITLE
Should we enable --cpu-manager-policy=static by default

### ISSUE THREAD

**Issue by mcastelino** [clearlinux/cloud-native-setup#71]
The static policy allows containers in Guaranteed pods with integer CPU requests access to exclusive CPUs on the node. This exclusivity is enforced using the cpuset cgroup controller.

https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/

**Comment by krsna1729** [comment]
@mcastelino we already flip flopped

https://github.com/clearlinux/cloud-native-setup/blob/935bb69cfda06c6c1d2c1d891d292b14963739f7/clr-k8s-examples/kubeadm.yaml#L10-L12

**Comment by krsna1729** [comment]
Until we make sure kata works we cannot turn on by default. If user is not interested in running kata they can uncomment and use
