### ISSUE TITLE
updates for  v1.14.0

### ISSUE THREAD

**Issue by hnanni** [clearlinux/cloud-native-setup#77]
Hello.
I started testing  k8s version v1.14.0. as:

`I0326 15:20:57.920018    2334 version.go:237] remote version is much newer: v1.14.0; falling back to: stable-1.13`

The following error shows that the configuration scripts will need updates:

```
+ sudo -E kubeadm init --config=./kubeadm.yaml
your configuration file uses a deprecated API spec:
"kubeadm.k8s.io/v1alpha3". Please use 'kubeadm config migrate --old-
config old.yaml --new-config new.yaml', which will write the new,
similar spec using a newer API version.
```

Is there a separate branch where this update is been worked out?

**Comment by krsna1729** [comment]
@hnanni How are you testing with 1.14. Did clearlinux update to 1.14 already?

**Comment by krsna1729** [comment]
try1: http://paste.ubuntu.com/p/YHWQznCqy4/
