### ISSUE TITLE
error running create_stack.sh

### ISSUE THREAD

**Issue by kiendinh** [clearlinux/cloud-native-setup#84]
I'm using the master branch @f863bb7f, and running create_stack.sh returned with this error:

`daemonset.apps/kata-deploy created
error: the path "8-kata/runtimeclass_crd.yaml" does not exist`

Looks like the latest commit removes the file that is required elsewhere. Could anyone please check?

**Comment by krsna1729** [comment]
@kiendinh Thanks for catching that. My mistake. Will test and fix up.
